name: DORA Metrics Report
on:
#   schedule:
#     - cron: "0 0 * * 1"  # Runs every Monday
  workflow_dispatch:   # Allows manual execution

permissions:
  contents: write  # Allow writing to repo
  actions: read    # Read workflow actions
  deployments: write  # Allow deployment access

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Repository Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics-1.json
          token: ${{ secrets.GITHUB_TOKEN }}
          base: repositories
          output_action: svg,json,png
          plugin_repositories: yes
          plugin_repositories_affiliations: owner, collaborator
          plugin_repositories_skipped: 0
          plugin_activity: yes
          plugin_activity_days: 30
          plugin_activity_visibility: public
          plugin_activity_filter: all
          plugin_traffic: yes
          plugin_traffic_days: 30
          plugin_lines: yes
          plugin_followup: yes
          plugin_followup_sections: repositories
          plugin_github_actions: yes
          plugin_github_actions_days: 30
          plugin_github_actions_visibility: public
          plugin_github_actions_status: all

      - name: Upload SVG as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dora-metrics-svg
          path: metrics-1.svg

      - name: Upload JSON as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dora-metrics-svg
          path: metrics-1.json

      - name: Upload PNG as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dora-metrics-svg
          path: metrics-1.png